project:
  type: website
  output-dir: docs

website:
  title: "veda-documentation"
  author: "VEDA Team (NASA IMPACT and Development Seed)"
  date: "3/31/2022"
  sidebar:
    contents:
    - index.qmd
    - veda-apis.qmd
    - section: "Example Notebooks"
      contents:
        - no2-timeseries.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



