project:
  type: book

book:
  title: "veda-documentation"
  author: "VEDA Team (NASA IMPACT and Development Seed)"
  date: "3/31/2022"
  chapters:
    - index.qmd
    - veda-apis.qmd
    - part: Example Notebooks
      chapters:
      - no2-timeseries.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



