project:
  type: website
  output-dir: docs

website:
  title: "VEDA Documentation"
  author: "VEDA Team (NASA IMPACT and Development Seed)"
  date: "3/31/2022"
  sidebar:
    contents:
      - index.qmd
      - veda-apis.qmd
      - tools.qmd
      - section: notebooks.qmd
        contents:
        - section: "Basic API Use"
          contents:
          - list-collections.ipynb
        - section: "Advanced API Use"
          contents:
          ## disable the 2 following notebooks since they rely on data 
          ## in MCP and github actions has no way to request short term
          ## access credentials to access the data
          - timeseries-rioxarray-stackstac.ipynb
          - open-and-plot.ipynb
          - timeseries-stac-api.ipynb
          - hls-visualization.ipynb
          - single-item-viz.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto




